import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { PortfolioItem } from '../types';
import { analyzePortfolio } from '../services/geminiService';
import { RefreshCw, Download, AlertOctagon, BrainCircuit } from 'lucide-react';

interface AnalysisViewProps {
  data: PortfolioItem[];
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ data }) => {
  const [markdown, setMarkdown] = useState<string>('');
  const [status, setStatus] = useState<'idle' | 'analyzing' | 'complete' | 'error'>('idle');
  const [errorMsg, setErrorMsg] = useState<string>('');

  const runAnalysis = async () => {
    setStatus('analyzing');
    setErrorMsg('');
    try {
      const result = await analyzePortfolio(data);
      setMarkdown(result);
      setStatus('complete');
    } catch (e: any) {
      setStatus('error');
      setErrorMsg(e.message || "Failed to generate analysis.");
    }
  };

  useEffect(() => {
    if (status === 'idle' && data.length > 0) runAnalysis();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="max-w-5xl mx-auto p-6 h-full flex flex-col">
      <header className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-3xl font-bold font-mono text-wallstreet-text">Investment Memo</h2>
          <p className="text-wallstreet-500 text-sm mt-1">Generated by Chief Macro Strategist AI</p>
        </div>
        <div className="flex gap-3">
          {status === 'complete' && (
            <button className="flex items-center gap-2 px-4 py-2 bg-wallstreet-700 hover:bg-wallstreet-600 rounded text-sm text-wallstreet-text transition-colors border border-wallstreet-600">
              <Download size={16} /> Export PDF
            </button>
          )}
          <button onClick={runAnalysis} disabled={status === 'analyzing'} className={`flex items-center gap-2 px-4 py-2 rounded text-sm font-bold transition-colors shadow-sm ${status === 'analyzing' ? 'bg-wallstreet-700 text-wallstreet-500 cursor-not-allowed' : 'bg-wallstreet-accent text-white hover:bg-sky-600'}`}>
            <RefreshCw size={16} className={status === 'analyzing' ? 'animate-spin' : ''} />
            {status === 'analyzing' ? 'Pressure Testing...' : 'Re-Run Analysis'}
          </button>
        </div>
      </header>

      {status === 'analyzing' && (
        <div className="flex-1 flex flex-col items-center justify-center min-h-[400px] text-center space-y-6">
          <div className="relative">
            <div className="absolute inset-0 bg-wallstreet-accent blur-xl opacity-20 animate-pulse"></div>
            <BrainCircuit size={64} className="text-wallstreet-accent relative z-10 animate-bounce" />
          </div>
          <div>
            <h3 className="text-xl font-mono text-wallstreet-text mb-2">Simulating Investment Committee</h3>
            <div className="text-wallstreet-500 space-y-1 font-mono text-sm">
              <p>Phase 1: Macro Overlay Check...</p>
              <p className="animate-pulse delay-75">Phase 2: Fundamental Stress Test...</p>
              <p className="animate-pulse delay-150">Phase 3: Correlation Analysis...</p>
              <p className="animate-pulse delay-200">Phase 4: Weight Variance Check...</p>
            </div>
          </div>
        </div>
      )}

      {status === 'error' && (
        <div className="p-6 bg-red-50 border border-red-200 rounded-xl flex items-start gap-4 text-red-600">
          <AlertOctagon size={24} className="mt-1 flex-shrink-0" />
          <div>
            <h3 className="font-bold mb-1">Analysis Failed</h3>
            <p>{errorMsg}</p>
            <p className="text-sm mt-2 opacity-75">Ensure your API Key is valid in .env.</p>
          </div>
        </div>
      )}

      {status === 'complete' && (
        <div className="prose prose-slate max-w-none bg-white p-8 rounded-xl border border-wallstreet-700 shadow-lg">
          <ReactMarkdown
            components={{
              h1: ({node, ...props}) => <h1 className="text-2xl font-mono font-bold text-wallstreet-accent border-b border-wallstreet-700 pb-2 mb-6 uppercase" {...props} />,
              h2: ({node, ...props}) => <h2 className="text-xl font-mono font-bold text-wallstreet-text mt-8 mb-4 flex items-center gap-2" {...props} />,
              h3: ({node, ...props}) => <h3 className="text-lg font-bold text-wallstreet-text mt-6 mb-2" {...props} />,
              strong: ({node, ...props}) => <strong className="text-wallstreet-text font-semibold" {...props} />,
              ul: ({node, ...props}) => <ul className="list-disc pl-5 space-y-2 text-wallstreet-text" {...props} />,
              p: ({node, ...props}) => <p className="mb-4 text-wallstreet-text leading-relaxed" {...props} />,
              li: ({node, ...props}) => <li className="pl-1" {...props} />,
              blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-wallstreet-accent pl-4 italic text-wallstreet-500 my-4" {...props} />
            }}
          >
            {markdown}
          </ReactMarkdown>
        </div>
      )}
    </div>
  );
};